//try CATCH
console.log(1 + 1);

try {
  autenticarUser();
} catch (error) {
  console.log(error);
}

console.log(2 + 2);
